articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

gis_1ban_2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

app_name ="accountapp"

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),

    path('subscribe/', include('subscribeapp.urls')),
    path('like/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like')
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

# SET_NULL = user가 삭제되어도 게시글은 작성자 미상으로 남음
# related_name은 나중에 유저와 연결할 때 사용되는 이름 ex) user.article
from projectapp.models import Project


class Article(models.Model):
    writer  = models.ForeignKey(User, on_delete=models.SET_NULL,
                               related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL,
                                related_name='article', null=True, blank=True)
    #  null=True 는 제목없음 가능
    title   = models.CharField(max_length=200, null=True)
    image   = models.ImageField(upload_to='article/', null=True)
    content = models.TextField(null=True)
    # 작성시간 입력
    # auto_now_add=True 는 게시글이 DB에 저장되는 시점을 기준으로 자동 입력
    # 따로 User에게 입력받거나 우리가 직접 입력해줄 수고로움을 덜 수 잇음
    created_at = models.DateField(auto_now_add=True)

    like = models.IntegerField(default=0)

templates/snippets/list_fragment.html
{% load static %}

    <style>
        .container {
            padding: 0;
            margin: 0 auto;
        }
        .container div {
              width: 45%;
                max-width: 200px;
              display: flex;
              justify-content: center;
              align-items: center;
              {# 1rem = 16px #}
              border-radius: 1rem;
                flex-direction: column;
                box-shadow: 0 0 1rem darkgray;
        }

        div img {
            width: 100%;
            border-radius: 1rem;
        }
    </style>
        {# my-5는 수직으로 5만큼 마진 여백 #}
    <div class="container my-3">
        {# 게시글을 이미지 기반으로 작성할 공간 #}
        {% for article in article_list %}
            <div>
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    <img src="{{ article.image.url }}" alt="">
                </a>
                <span class="NNS_B m-2">{{ article.title }}</span>
            </div>
        {% endfor %}
    </div>

    {# 외부에서 스크립트 가져오기 #}
    <script src="{% static 'js/magicgrid.js' %}"></script>
    {# 페이지 넘버를 표현하는 방법이나 스타일을 저장하는 html을 따로 만들어서 불러오기 #}
    {% include 'snippets/pagination.html' %}

    <div class="text-center my-5">
        <a href="{% url 'articleapp:create' %}"
           class="btn btn-dark rounded-pill material-icons">
            brush
        </a>
        <a href="{% url 'articleapp:create' %}"
           class="btn btn-outline-dark rounded-pill px-5">
           Create Article
        </a>
    </div>

templates/snippets/pagination.html
    <div class="text-center my-5">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}"
               class="btn btn-secondary rounded-pill">
                {{ page_obj.previous_page_number }}
            </a>

        {% endif %}
        {# 어디로 이동하지 않고 현재 화면에서 머무르기 #}
            <a href="#"
               class="btn btn-dark rounded-pill">
                {# 현재 페이지 넘버 출력 #}
                {{ page_obj.number }}
            </a>
        {# 다음 페이지 있는지 여부를 확인 #}
        {% if page_obj.has_next %}
            {# 페이지 넘버를 get 방식으로 받기 때문에 주소창에 쿼리로 입력하면 됨 #}
            <a href="?page={{ page_obj.next_page_number }}"
               class="btn btn-secondary rounded-pill">
                {{ page_obj.next_page_number }}
            </a>
        {% endif %}
    </div>