articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

commentapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView, CommentDeleteView

app_name = 'commentapp'

urlpatterns = [
    path('create/', CommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>', CommentDeleteView.as_view(), name='delete'),
]

gis_1ban_2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

app_name ="accountapp"

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),

    path('subscribe/', include('subscribeapp.urls')),
    path('like/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like')
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

# SET_NULL = user가 삭제되어도 게시글은 작성자 미상으로 남음
# related_name은 나중에 유저와 연결할 때 사용되는 이름 ex) user.article
from projectapp.models import Project


class Article(models.Model):
    writer  = models.ForeignKey(User, on_delete=models.SET_NULL,
                               related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL,
                                related_name='article', null=True, blank=True)
    #  null=True 는 제목없음 가능
    title   = models.CharField(max_length=200, null=True)
    image   = models.ImageField(upload_to='article/', null=True)
    content = models.TextField(null=True)
    # 작성시간 입력
    # auto_now_add=True 는 게시글이 DB에 저장되는 시점을 기준으로 자동 입력
    # 따로 User에게 입력받거나 우리가 직접 입력해줄 수고로움을 덜 수 잇음
    created_at = models.DateField(auto_now_add=True)

    like = models.IntegerField(default=0)

articleapp/forms.py
from django import forms
from django.forms import ModelForm

from articleapp.models import Article


class ArticleCreationForm(ModelForm):
    # models.py에서는 models.~~였다면 forms.py에서는 forms.~~로 시작
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'editable',
                                                           'style': 'text-align: left;'
                                                                    'min-height: 10rem;'}))

    class Meta:
        model = Article
        # 클라이언트에게 입력받아야 될 요소
        fields = ['title', 'image', 'project', 'content']

articleapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article
from commentapp.forms import CommentCreationForm


class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        form.instance.writer = self.request.user
        return super().form_valid(form)


class ArticleDetailView(DetailView, FormMixin):
    model = Article
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'

@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk':self.object.pk})

@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/delete.html'


class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 20

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
<link rel="stylesheet" href="{% static 'beagle.css' %}">

<div class="text-center mw-500 m-auto">
    <div class="m-5">
        <h4>Create Article</h4>
    </div>
    <div>
        <form action="{% url 'articleapp:create' %}"
              method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="m-5">
                <input type="submit"
                   class="btn-dark rounded-pill px-5">
            </div>
        </form>

    </div>

</div>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="text-center mw-500 m-auto">
    <div class="m-5">
        <h4>Delete Article : {{ target_article.title }}</h4>
    </div>
    <div>
        <form action="{% url 'articleapp:delete' pk=target_article.pk %}"
              method="post">
            {% csrf_token %}
            <div class="m-5">
                <input type="submit"
                   class="btn-dark rounded-pill px-5">
            </div>
        </form>

    </div>

</div>

{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="container text-center">

        <div class="my-5">
            {# 제목 / 글쓴이 / 날짜 #}
            <h1 class="NNS_B">{{ target_article.title }}</h1>
            {# 좋아요 버튼 만들기 #}
            <div class="my-3">
                <a href="{% url 'likeapp:article_like' article_pk=target_article.pk %}"
                   class="material-icons"
                   style="vertical-align: middle; color: #f77">
                   favorite
                </a>
                <span style="vertical-align: middle">
                    {{ target_article.like }}
                </span>
            </div>
            {# writer(user)의 프로필에 있는 닉네임을 표시 #}
            <h4>{{ target_article.writer.profile.nickname }}</h4>
            <p>{{ target_article.created_at }}</p>
        </div>
        <hr>
        <div class="my-5">
            {# 게시글 내용 #}
            <img src="{{ target_article.image.url }}"
                 alt=""
                 class="article_image">

            <div class="article_content">
                 {{ target_article.content | safe }}
            </div>

            {# 유저와 작성자가 일치할 때만 버튼 노출 #}
            {% if target_article.writer == user %}
            {# 게시글 상세페이지 내에 Button 만들기 #}
            <div>
                {# 동그란 알약 모양으로 버튼을 만들고 px-5는 x축으로 padding값을 5 준다는 의미. #}
                <a href="{% url 'articleapp:update' pk=target_article.pk %}"
                   class="btn btn-success rounded-pill px-5">
                   Update
                </a>
                <a href="{% url 'articleapp:detail' pk=target_article.pk %}"
                   class="btn btn-danger rounded-pill px-5">
                   Delete
                </a>
            </div>
            {% endif %}
        </div>
        <hr>
        <div class="text-center my-4">
            {# 댓글 #}
            {# comment 시각화 #}
            {# comment는 프로필이나 계정처럼 하나씩만 있는 것이 아니기 때문에 모두 가져온다는 것(.all)을 추가 #}
            {% for comment in target_article.comment.all %}
                {# 외곽선(border)을 실선(solid) #}
                <div class="comment_box">
                    <div>
                        <span style="font-size: 1.3rem;" class="NNS_B">
                            {{ comment.writer.profile.nickname }}</span>
                        <span>{{ comment.created_at }}</span>
                    </div>
                    <div class="my-2">
                        <p>{{ comment.content }}</p>
                    </div>
                    {% if comment.writer == user %}
                    <div style="text-align: right">
                        <a href="{% url 'commentapp:delete' pk=comment.pk %}"
                           class="btn btn-danger rounded-pill px-5">
                           Delete
                        </a>
                    </div>
                    {% endif %}
                </div>
            {% endfor %}
            {# 댓글 #}
            {% include 'commentapp/create.html' %}
        </div>

    </div>

{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <style>
        .container {
            padding: 0;
            margin: 0 auto;
        }
        .container div {
              width: 45%;
                max-width: 200px;
              display: flex;
              justify-content: center;
              align-items: center;
              border-radius: 1rem;
                flex-direction: column;
                box-shadow: 0 0 1rem darkgray;
    }

        div img {
            width: 100%;
            border-radius: 1rem;
        }
    </style>

    <div class="container">
          {% for article in article_list %}

              <div>
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    <img src="{{ article.image.url }}" alt="">
                </a>
                <span class="NNS_B m-2">{{ article.title }}</span>
            </div>

          {% endfor %}
    </div>

    {# 외부에서 스크립트 가져오기 #}
    <script src="{% static 'js/magicgrid.js' %}"></script>

    {% include 'snippets/pagination.html'  %}

    <div class="text-center my-5">
        <a href="{% url 'articleapp:create' %}"
           class="btn btn-dark rounded-pill material-icons">
           brush
        </a>
        <a href="{% url 'articleapp:create' %}"
           class="btn btn-outline-dark rounded-pill px-5">
           Create Article
        </a>
    </div>

{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
<link rel="stylesheet" href="{% static 'beagle.css' %}">

<div class="text-center mw-500 m-auto" >
    <div class="m-5">
        <h4>Update Article</h4>
    </div>
    <div>
        <form action="{% url 'articleapp:update' pk=target_article.pk %}"
              method="post" enctype="multipart/form-data">
            {# Django에서 기본적으로 제공하는 보안 시스템 #}
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="m-5">
                <input type="submit"
                       class="btn-dark rounded-pill px-5">
            </div>
        </form>
    </div>
</div>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}